export const artists = [
    {
        title: "Taylor Swift",
        text: `This vegetarian, vegan and gluten-free mushroom burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this veggie burger recipe high in fiber and protein too. There's not much to them, other than that! Just mash everything up together, form into patties, heat and serve!`,
        image: 'https://images.wsj.net/im-434274?width=1920',
        dateAdded: new Date("2023/01/19"),
        location: "Stockholm",
        date: new Date(2023, 6, 20),
        totalSeats: 200,
        availableSeats: 200,
        isBought: false,
        wishList: false,

    },
    {
        title: "Harry Styles",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/20"),
        location: "Uppsala",
        date: new Date("2023/06/21"),
        totalSeats: 150,
        availableSeats: 150,
        isBought: false,
        wishList: false,
    },
    {
        title: "Kayne West",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/21"),
        location: "Borås",
        date: new Date("2023/04/19"),
        totalSeats: 205,
        availableSeats: 205,
        isBought: false,
        wishList: false,
    },
    {
        title: "Kimberly Amethyst",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/22"),
        location: "Sövde",
        date: new Date("2023/03/01"),
        totalSeats: 2005,
        availableSeats: 2005,
        isBought: false,
        wishList: false,
    },
    {
        title: "Eminem",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/22"),
        location: "Berlin",
        date: new Date("2023/12/21"),
        totalSeats: 250,
        availableSeats: 250,
        isBought: false,
        wishList: false,
    },
    {
        title: "Kimberly Amethyst",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/23"),
        location: "Malmö",
        date: new Date("2023/11/19"),
        totalSeats: 120,
        availableSeats: 120,
        isBought: false,
        wishList: false,
    },
    {
        title: "Madonna",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/01/30"),
        location: "Kina",
        date: new Date("2023/06/20"),
        totalSeats: 125,
        availableSeats: 125,
        isBought: false,
        wishList: false,
    },
    {
        title: "Bob Dylan",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/02/01"),
        location: "Borås",
        date: new Date('2023/01/27'),
        totalSeats: 200,
        availableSeats: 200,
        isBought: false,
        wishList: false,
    },
    {
        title: "Rihanna",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2023/02/01"),
        location: "Lund",
        date: new Date("2023/06/22"),
        totalSeats: 225,
        availableSeats: 200,
        isBought: false,
        wishList: false,
    },
    {
        title: "Elton John",
        text: `Mushrooms are surprisingly similar in taste and texture to meat when cooked, and this mushroom veggie burger recipe may just surprise you with how tasty it is. While mushrooms provide plenty of flavor and texture, the addition of pinto beans makes this recipe high in fiber and protein too. `,
        image: 'https://veryveganrecipes.com/wp-content/uploads/2015/12/how-to-make-vegan-portobello-mushroom-burger-recipe.png',
        dateAdded: new Date("2022/03/23"),
        location: "Blentarp",
        date: new Date("2024/01/20"),
        totalSeats: 300,
        availableSeats: 200,
        isBought: false,
        wishList: false,
    }
]